### ISSUE TITLE
Infografía: Realidad Aumentada 

### ISSUE THREAD

**Issue by 10154** [SistemasTecTlaxiaco/infografia-10154#1]
[Infografia Alexis Castañeda Sánchez.pdf](https://github.com/SistemasTecTlaxiaco/infografia-10154/files/8054895/Infografia.Alexis.Castaneda.Sanchez.pdf)

**Comment by Eva155** [comment]
La infografía cuenta con todos los puntos que marca la rúbrica, la información es organizada, tiene coherencia, es por ello que se le asigna la calificación de 20 PUNTOS.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
