### ISSUE TITLE
Infografía ALexis Castañeda Sánchez

### ISSUE THREAD

**Issue by 10154** [SistemasTecTlaxiaco/infografia-10154#2]
![Infografia Alexis Castañeda Sánchez](https://user-images.githubusercontent.com/72049151/111841137-178c4100-88c3-11eb-92a4-8710f6c7a14d.jpg)

**Comment by dulce-blm** [comment]
La infografía cumple con todos los criterios. Calificación 20 puntos.

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado solo que el tiempo de entrega se excedio.

**Comment by josealfredo79** [comment]
Entonces  ya se verifico correctamente la entrega de la infografia.
